### PR TITLE
Features/progress

### PR DESCRIPTION
**Pull request by raulsouzalima**
When working with big files, it's important to have a progress callback of the downloaded file, so, this pull request implements this.

### CODE REVIEW

**Comment by dukex** [comment]
Awesome! +1

**Comment by Stuk** [comment]
I really like the idea, but this breaks the convention of the last argument being an errback. 

Although I dislike optional arguments that aren't last, it might be best here to put the progress callback as the second argument. Alternatively we could have an options object. 

I'm traveling at the moment, so I'll have to think about this some more

**Comment by bbottema** [comment]
What happened to this?

**Comment by dukex** [comment]
The progress callback could be a opcional argument

**Comment by Stuk** [comment]
Functionality released as part of v0.1.0

**Pull request closed without merging**
